In [31]:
import pandas as pd

era_df = pd.read_csv('exploring-data/era5-germany-july-september-2022.csv')

In [32]:
era_df.sample(5)

,valid_time,latitude,longitude,u10,v10,t2m,tcc,tp,ssrd
464,2022-07-20 09:00:00,51.0,10.0,-1.453644,2.502930,30.777130,0.246735,0.000000,493312.0
246,2022-07-11 07:00:00,51.0,10.0,1.019882,-2.069565,14.175201,0.970551,0.000111,20224.0
584,2022-07-25 09:00:00,51.0,10.0,1.073273,3.540253,29.678253,0.000000,0.000000,488320.0
2096,2022-09-26 09:00:00,51.0,10.0,3.557098,4.561096,10.731110,0.656525,0.000181,543680.0
2083,2022-09-25 20:00:00,51.0,10.0,1.218948,-0.418549,10.843536,0.977509,0.000000,0.0

In [33]:
era_df = era_df.rename(columns={'valid_time': 'Datetime (UTC)'})

In [34]:
era_df.sample()

,Datetime (UTC),latitude,longitude,u10,v10,t2m,tcc,tp,ssrd
1067,2022-08-14 12:00:00,51.0,10.0,-2.853104,1.913086,28.087982,0.514252,0.0,0.0

In [35]:
era_df = era_df.drop(columns=['latitude', 'longitude'])

In [36]:
era_df.sample()

          Datetime (UTC)      u10       v10        t2m  tcc   tp     ssrd
316  2022-07-14 05:00:00 -1.09613 -1.947708  16.642853  1.0  0.0  82560.0

In [37]:
era_df.isnull().sum()

Datetime (UTC)    0
u10               0
v10               0
t2m               0
tcc               0
tp                0
ssrd              0
dtype: int64

In [38]:
price_df = pd.read_csv('exploring-data/electricity-price-july-september-2022.csv')

In [39]:
price_df.sample(5)

,Country,ISO3 Code,Datetime (UTC),Datetime (Local),Price (EUR/MWhe)
1419,Germany,DEU,2022-08-29 03:00:00,2022-08-29 05:00:00,567.20
284,Germany,DEU,2022-07-12 20:00:00,2022-07-12 22:00:00,454.50
2152,Germany,DEU,2022-09-28 16:00:00,2022-09-28 18:00:00,513.64
911,Germany,DEU,2022-08-07 23:00:00,2022-08-08 01:00:00,281.94
1657,Germany,DEU,2022-09-08 01:00:00,2022-09-08 03:00:00,367.19

In [40]:
price_df = price_df.rename(columns={'valid_time': 'Datetime (UTC)'})

In [41]:
price_df.isnull().sum()

Country             0
ISO3 Code           0
Datetime (UTC)      0
Datetime (Local)    0
Price (EUR/MWhe)    0
dtype: int64

In [42]:
price_df = price_df.drop(columns=['Datetime (Local)', 'ISO3 Code'])
price_df.sample()

     Country       Datetime (UTC)  Price (EUR/MWhe)
934  Germany  2022-08-08 22:00:00            331.01

In [43]:
pvgis_df = pd.read_csv('exploring-data/pvgis-germany-2022.csv')

In [44]:
pvgis_df.sample(5)

               time      P  G(i)  H_sun    T2m  WS10m  Int
5736  20220828:0010   0.00   0.0   0.00  15.11   1.52  0.0
6957  20221017:2110   0.00   0.0   0.00  15.68   1.93  0.0
3667  20220602:1910   0.00   0.0   0.00  14.93   2.41  0.0
8457  20221219:0910  18.57  34.0  10.56   0.25   4.41  0.0
7270  20221030:2210   0.00   0.0   0.00  13.08   1.93  0.0

In [45]:
pvgis_df = pvgis_df.rename(columns={'time': 'Datetime (UTC)'})

In [46]:
pvgis_df = pvgis_df.drop(columns=['Int'])

In [47]:
pvgis_df.sample()

     Datetime (UTC)    P  G(i)  H_sun   T2m  WS10m
8393  20221216:1710  0.0   0.0    0.0 -5.94   1.72

In [48]:
pvgis_df['Datetime (UTC)'] = pd.to_datetime(
    pvgis_df['Datetime (UTC)'].astype(str),
    format='%Y%m%d:%H%M'
)

In [49]:
pvgis_df

          Datetime (UTC)    P  G(i)  H_sun    T2m  WS10m
0    2022-01-01 00:10:00  0.0   0.0    0.0  10.18   3.72
1    2022-01-01 01:10:00  0.0   0.0    0.0  10.07   3.38
2    2022-01-01 02:10:00  0.0   0.0    0.0   9.98   2.97
3    2022-01-01 03:10:00  0.0   0.0    0.0   9.88   2.76
4    2022-01-01 04:10:00  0.0   0.0    0.0   9.76   2.90
...                  ...  ...   ...    ...    ...    ...
8755 2022-12-31 19:10:00  0.0   0.0    0.0  13.32   5.52
8756 2022-12-31 20:10:00  0.0   0.0    0.0  13.36   5.72
8757 2022-12-31 21:10:00  0.0   0.0    0.0  13.36   5.93
8758 2022-12-31 22:10:00  0.0   0.0    0.0  13.36   6.00
8759 2022-12-31 23:10:00  0.0   0.0    0.0  13.24   5.93

[8760 rows x 6 columns]

In [50]:
era_df

,Datetime (UTC),u10,v10,t2m,tcc,tp,ssrd
0,2022-07-01 01:00:00,2.669998,-0.490677,18.401154,1.000000,0.000174,0.0
1,2022-07-01 02:00:00,5.843552,0.322693,16.314117,1.000000,0.000242,0.0
2,2022-07-01 03:00:00,4.419983,-1.093002,14.973541,1.000000,0.000000,0.0
3,2022-07-01 04:00:00,1.841629,-2.487869,14.196320,1.000000,0.000000,22464.0
4,2022-07-01 05:00:00,1.882843,-1.151215,13.689545,0.998505,0.000624,57600.0
...,...,...,...,...,...,...,...
2202,2022-09-30 19:00:00,0.431381,2.671600,8.399506,0.281250,0.000000,0.0
2203,2022-09-30 20:00:00,0.714874,2.838486,7.761444,0.010498,0.000000,0.0
2204,2022-09-30 21:00:00,0.971848,2.612183,7.278046,0.011993,0.000000,0.0
2205,2022-09-30 22:00:00,1.020859,3.566208,7.417389,1.000000,0.000000,0.0
2206,2022-09-30 23:00:00,0.894058,3.763351,7.708160,1.000000,0.000000,0.0

In [51]:
era_df['Datetime (UTC)'] = pd.to_datetime(era_df['Datetime (UTC)'])
price_df['Datetime (UTC)'] = pd.to_datetime(price_df['Datetime (UTC)'])
pvgis_df['Datetime (UTC)'] = pd.to_datetime(pvgis_df['Datetime (UTC)'])

pvgis_df['Datetime (UTC)'] = pvgis_df['Datetime (UTC)'].dt.floor('h')

print('era_df sample:', era_df['Datetime (UTC)'].iloc[0])
print('price_df sample:', price_df['Datetime (UTC)'].iloc[0])
print('pvgis_df sample:', pvgis_df['Datetime (UTC)'].iloc[0])

era_df sample: 2022-07-01 01:00:00
price_df sample: 2022-07-01 00:00:00
pvgis_df sample: 2022-01-01 00:00:00

In [52]:
merged = pd.merge(era_df, price_df, on='Datetime (UTC)', how='inner')
print('era + price shape:', merged.shape)

final_df = pd.merge(merged, pvgis_df, on='Datetime (UTC)', how='inner')
print('merged + pvgis shape:', merged.shape)
final_df.head()

era + price shape: (2207, 9)

,Datetime (UTC),u10,v10,t2m,tcc,tp,ssrd,Country,Price (EUR/MWhe),P,G(i),H_sun,T2m,WS10m
0,2022-07-01 01:00:00,2.669998,-0.490677,18.401154,1.000000,0.000174,0.0,Germany,259.62,0.00,0.0,0.00,19.24,3.72
1,2022-07-01 02:00:00,5.843552,0.322693,16.314117,1.000000,0.000242,0.0,Germany,259.64,0.00,0.0,0.00,17.75,3.59
2,2022-07-01 03:00:00,4.419983,-1.093002,14.973541,1.000000,0.000000,0.0,Germany,270.50,0.00,0.0,0.00,16.43,3.03
3,2022-07-01 04:00:00,1.841629,-2.487869,14.196320,1.000000,0.000000,22464.0,Germany,339.78,0.48,7.0,7.16,15.47,2.76
4,2022-07-01 05:00:00,1.882843,-1.151215,13.689545,0.998505,0.000624,57600.0,Germany,378.23,6.96,19.0,15.85,14.57,2.55

In [55]:
final_df.to_csv('exploring-data/final-dataset.csv', index=False)