In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/pvgis-raw.csv')

In [3]:
df.head()

            time    P  Gb(i)  Gd(i)  Gr(i)  H_sun    T2m  WS10m  Int
0  20230101:0030  0.0    0.0    0.0    0.0    0.0  13.41   6.41  0.0
1  20230101:0130  0.0    0.0    0.0    0.0    0.0  13.28   6.21  0.0
2  20230101:0230  0.0    0.0    0.0    0.0    0.0  13.05   6.00  0.0
3  20230101:0330  0.0    0.0    0.0    0.0    0.0  12.64   6.00  0.0
4  20230101:0430  0.0    0.0    0.0    0.0    0.0  12.32   6.21  0.0

In [4]:
df['time'] = df['time'].str.replace(
    r'(\d{4})(\d{2})(\d{2}):(\d{2})(\d{2})',
    r'\1-\2-\3 \4:\5',
    regex=True
)

In [5]:
df['time'].sample()

7613    2023-11-14 05:30
Name: time, dtype: object

In [6]:
df = df.rename(columns={'time': 'Datetime (UTC)'})

In [7]:
df.head()

     Datetime (UTC)    P  Gb(i)  Gd(i)  Gr(i)  H_sun    T2m  WS10m  Int
0  2023-01-01 00:30  0.0    0.0    0.0    0.0    0.0  13.41   6.41  0.0
1  2023-01-01 01:30  0.0    0.0    0.0    0.0    0.0  13.28   6.21  0.0
2  2023-01-01 02:30  0.0    0.0    0.0    0.0    0.0  13.05   6.00  0.0
3  2023-01-01 03:30  0.0    0.0    0.0    0.0    0.0  12.64   6.00  0.0
4  2023-01-01 04:30  0.0    0.0    0.0    0.0    0.0  12.32   6.21  0.0

In [8]:
df = df.drop(columns=['Int'])

In [9]:
df.head()

     Datetime (UTC)    P  Gb(i)  Gd(i)  Gr(i)  H_sun    T2m  WS10m
0  2023-01-01 00:30  0.0    0.0    0.0    0.0    0.0  13.41   6.41
1  2023-01-01 01:30  0.0    0.0    0.0    0.0    0.0  13.28   6.21
2  2023-01-01 02:30  0.0    0.0    0.0    0.0    0.0  13.05   6.00
3  2023-01-01 03:30  0.0    0.0    0.0    0.0    0.0  12.64   6.00
4  2023-01-01 04:30  0.0    0.0    0.0    0.0    0.0  12.32   6.21

In [10]:
df.isna().sum()

Datetime (UTC)    0
P                 8
Gb(i)             9
Gd(i)             9
Gr(i)             9
H_sun             9
T2m               9
WS10m             9
dtype: int64

In [11]:
df = df.dropna(subset=['P'])

In [12]:
df.isna().sum()

Datetime (UTC)    0
P                 0
Gb(i)             1
Gd(i)             1
Gr(i)             1
H_sun             1
T2m               1
WS10m             1
dtype: int64

In [13]:
df = df.dropna(subset=['Gb(i)', 'Gd(i)', 'Gr(i)', 'H_sun', 'T2m', 'WS10m'])

In [14]:
df.isna().sum()

Datetime (UTC)    0
P                 0
Gb(i)             0
Gd(i)             0
Gr(i)             0
H_sun             0
T2m               0
WS10m             0
dtype: int64

In [15]:
df.head()

     Datetime (UTC)    P  Gb(i)  Gd(i)  Gr(i)  H_sun    T2m  WS10m
0  2023-01-01 00:30  0.0    0.0    0.0    0.0    0.0  13.41   6.41
1  2023-01-01 01:30  0.0    0.0    0.0    0.0    0.0  13.28   6.21
2  2023-01-01 02:30  0.0    0.0    0.0    0.0    0.0  13.05   6.00
3  2023-01-01 03:30  0.0    0.0    0.0    0.0    0.0  12.64   6.00
4  2023-01-01 04:30  0.0    0.0    0.0    0.0    0.0  12.32   6.21

In [16]:
df['P'].value_counts()

P
0.0       4438
38.88        4
43.0         4
0.15         4
0.46         4
          ...
223.76       1
150.34       1
108.59       1
34.8         1
10.68        1
Name: count, Length: 3995, dtype: int64

In [17]:
df['Datetime (UTC)'].head(5)

0    2023-01-01 00:30
1    2023-01-01 01:30
2    2023-01-01 02:30
3    2023-01-01 03:30
4    2023-01-01 04:30
Name: Datetime (UTC), dtype: object

In [18]:
df['Datetime (UTC)'] = pd.to_datetime(df['Datetime (UTC)'])
df['Datetime (UTC)'] = df['Datetime (UTC)'] - pd.Timedelta(minutes=30)

In [19]:
df['Datetime (UTC)'].head(5)

0   2023-01-01 00:00:00
1   2023-01-01 01:00:00
2   2023-01-01 02:00:00
3   2023-01-01 03:00:00
4   2023-01-01 04:00:00
Name: Datetime (UTC), dtype: datetime64[ns]

In [20]:
df.to_csv('pvgis.csv', index=False)